### ISSUE TITLE
Improve `svd2rust`'s logging story

### ISSUE THREAD

**Issue by jamesmunns** [rust-embedded/svd2rust#183]
Currently there is only output on STDERR when some subset of failures occur. There is no feedback for items such as:

* Empty Registers
* Skipped Peripherals

Additionally, there are no different levels of logging, as of now all output is written directly to stderr.

We should consider adding:
* some kind of granular logging system, maybe using `slog` or `env_logger`
* additional error, warning, and info logs usable for development or troubleshooting

**Comment by achan1989** [comment]
As a starter I can introduce a logging system, but keep the existing "error and warning messages get printed to stderr" behaviour.

What's the desired end goal?  Print info and higher to stderr by default, and use a `-v` command-line switch to enable debug-level log printing?

**Comment by adamgreig** [comment]
#237 adds a logging system, so I'm closing this issue. If we need to improve logging further please open a subsequent issue.
