### ISSUE TITLE
save access to unions

### ISSUE THREAD

**Issue by burrbull** [rust-embedded/svd2rust#230]
With --nightly option svd2rust now can generate unions:
```
#[doc = "capture/compare mode register 1 (input\n          mode) capture/compare mode register (output\n          mode)"]
#[repr(C)]
pub union Ccmr1Union {
    #[doc = "0x18 - capture/compare mode register 1 (input mode)"]
    pub ccmr1_input: CCMR1_INPUT,
    #[doc = "0x18 - capture/compare mode register (output mode)"]
    pub ccmr1_output: CCMR1_OUTPUT,
}
```

I think it makes sense to add save access to contents.
Something like:
```
impl Ccmr1Union {
    #[doc = "ccmr1.input()"]
    pub fn input(&self) -> &CCMR1_INPUT {
        unsafe { &self.ccmr1_input }
    }
    #[doc = "ccmr1.ouput()"]
    pub fn output(&self) -> &CCMR1_OUTPUT {
        unsafe { &self.ccmr1_output }
    }
}
```

**Comment by wez** [comment]
I'm taking a stab at this in https://github.com/wez/svd2rust/tree/no_unions

**Comment by wez** [comment]
@burrbull oh, that's bad.  Can you point me to the svd file you're using?  That doesn't happen with the ATSAMD files I'm using and I'd like to make sure this is working

**Comment by wez** [comment]
ah, never mind, I can see that it is happening here

**Comment by wez** [comment]
pushed a fix; thanks for catching that!
