### ISSUE TITLE
Escape `[` and `]` in svd description before it is used in the doc attribute

### ISSUE THREAD

**Issue by Nicoretti** [rust-embedded/svd2rust#232]
Hi @all,

I generated some peripherals using **svd2rust** and stumbled upon an issue with **missing escape sequences** for characters which should be escaped **in the docstrings**.

**Issue:**
Missing escape sequence for `[` and `]` in generated docstrings.

**Impact:**
Documentation generation will fail.

**Steps to reproduce:**
1. Download [Keil.STM32F4xx_DFP.2.13.0.pack](https://keilpack.azureedge.net/pack/Keil.STM32F4xx_DFP.2.13.0.pack)
   The .pack file actually is a zip file
2. Unzip the .pack file and find the get STM32F41x.svd file
    (CMSIS/SVD/STM32F41x.svd)
3. Run the following svd2rust command
    `svd2rust -i STM32F41x.svd --target "cortex-m"`
4. Add the generated .rs file to some crate
5. Try to generate the documentation for that crate

**Summary**
If an .svd file contains a description with the characters `[` and `]`
e.g.:
```     
    <interrupt>
         <name>EXTI9_5</name>
         <description>EXTI Line[9:5] interrupts</description>
         <value>23</value>
     </interrupt>
```
**svd2rust** will generate a docstring missing necessary escapes for `[` and `]`:

```    
    #[doc = "23 - EXTI Line[9:5] interrupts"]
    EXTI9_5,
```
this will prevent `cargo doc` from generating documentation for the generated file:
```
error: `[9:5]` cannot be resolved, ignoring it...
   --> peripherals/src/lib.rs:259:23
    |
259 |     #[doc = "23 - EXTI Line[9:5] interrupts"]
    |                       ^^^ cannot be resolved, ignoring
    |
note: lint level defined here
   --> peripherals/src/lib.rs:3:12
    |
3   | #![ deny ( warnings ) ]
    |            ^^^^^^^^
    = note: #[deny(intra_doc_link_resolution_failure)] implied by #[deny(warnings)]
    = help: to escape `[` and `]` characters, just add '\' before them like `\[` or `\]`
```

**Attention:**
The suggested cargo/rustc fix will work, but be aware that in order to achiev `\[` you need to write `\\[` I guess this is due to the fact that we need create an escape sequence for the "docstring"  and not for the string itself.

A quick search brought up this spots in the code where such an error might happen: 
```
src/generate/interrupt.rs|59| #[doc = #description]
src/generate/peripheral.rs|38| #[doc = #description]
src/generate/peripheral.rs|100| #[doc = #description]
src/generate/peripheral.rs|403| #[doc = #comment]
src/generate/peripheral.rs|480| #[doc = #comment]
src/generate/peripheral.rs|505| #[doc = #description]
src/generate/peripheral.rs|513| #[doc = #description]
src/generate/peripheral.rs|754| #[doc = #description]
src/generate/register.rs|187| #[doc = #description]
src/generate/register.rs|192| #[doc = #description]
src/generate/register.rs|358| #[doc = #desc]
src/generate/register.rs|366| #[doc = #desc]
src/generate/register.rs|371| #[doc = #desc]
src/generate/register.rs|380| #[doc = #description]
src/generate/register.rs|396| #[doc = #desc]
src/generate/register.rs|408| #[doc = #desc]
src/generate/register.rs|505| #[doc = #doc]
src/generate/register.rs|524| #[doc = #description]
src/generate/register.rs|619| #[doc = #pc_w_doc]
src/generate/register.rs|632| #[doc = #pc_w_doc]
src/generate/register.rs|642| #[doc = #pc_w_doc]
src/generate/register.rs|687| #[doc = #pc_w_doc]
src/generate/register.rs|689| #(#[doc = #variants_doc]
src/generate/register.rs|734| #[doc = #doc]
src/generate/register.rs|742| #[doc = #doc]
src/generate/register.rs|794| #[doc = #description]
```

**Comment by ryankurte** [comment]
Thanks for the issue and PR! #233 looks like a reasonable solution to me.
 
We seem to be a bit inconsistent with where `util::respace` is called. I wonder whether we should be calling both at all those sites (cc. @jamesmunns)?

**Comment by Nicoretti** [comment]
@jamesmunns would it make sense to add the document generation to the regression testing?

**Comment by jamesmunns** [comment]
I'll take a look at this (and #233) when I get a chance, but tbh I haven't looked too deeply in how the doc comment generation process works.

@Nicoretti yes, I think that would make sense to add to both svd2rust_regress and the main travis CI.

**Comment by wez** [comment]
FWIW, as a crappy but effective workaround, I've been adding `#![allow(intra_doc_link_resolution_failure)]` to the generated crates
