### ISSUE TITLE
Consistent creation of GPIO RegisterBlocks

### ISSUE THREAD

**Issue by HarkonenBade** [rust-embedded/svd2rust#268]
Based on https://github.com/stm32-rs/stm32-rs/issues/115 . It would be helpful for definitions of GPIO structures that use `derivedFrom` to generate an aliasing type (e.g.  `mod gpiob { pub type RegisterBlock = gpiof::RegisterBlock}`), such that you can always have a consistent path to the RegisterBlock type for a given GPIO port.

**Comment by burrbull** [comment]
We reexport modules. So I don't think this is issue now. Reopen if it is not.
