### ISSUE TITLE
cargo test doesn't work at master

### ISSUE THREAD

**Issue by cbiffle** [rust-embedded/svd2rust#271]
I'm trying to send y'all a patch, so I followed my normal process for contributing to a Rust project:

```
$ git clone https://github.com/rust-embedded/svd2rust.git
$ cd svd2rust
$ cargo test
```

...to get a baseline before potentially breaking things.

It looks like the codebase contains 19 failing doctests, which all reference API from external crates like `cortex_m` and `stm32`. Am I doing something wrong? Shall I send a PR to fix or `ignore` these tests?

Thanks in advance.

**Comment by jamesmunns** [comment]
Hm, it seems we don't run `cargo test` on svd2rust itself in the CI. Yes, it would be great to have these fixes, and if you could add this check to https://github.com/rust-embedded/svd2rust/blob/master/ci/script.sh - it would be greatly appreciated!
