### ISSUE TITLE
Decrease CI output verbosity

### ISSUE THREAD

**Issue by ryankurte** [rust-embedded/svd2rust#291]
Some [tests](https://travis-ci.org/rust-embedded/svd2rust/jobs/498963079#L635) with small errors fail with:
> The job exceeded the maximum log length, and has been terminated.
because the generated rust files are a single line, so the error trace is the entire generated file.

i think this could be remedied by adding a `cargo fmt` pass [here](https://github.com/rust-embedded/svd2rust/blob/master/ci/script.sh#L18), or by teaching svd2rust to format created files as part of the process.

**Comment by Emilgardis** [comment]
rustfmt was removed in #269 due to slow build time. I don't think it improved performance too much though. https://github.com/rust-embedded/svd2rust/pull/269#issuecomment-448166840_ is something I would like to see implemented however.

> My suggestion would be to only format crates that fail (which can be done both in svd2rust-regress and the sh script).
