### ISSUE TITLE
Warn or fail on unknown tags?

### ISSUE THREAD

**Issue by laanwj** [rust-embedded/svd2rust#296]
I had a typo here, specifying `enumerateValue` instead of `enumeratedValue`, and the parser silently ignored it: https://github.com/riscv-rust/k210-pac/pull/23
Would be convenient if these unknown tags were flagged with a warning at least.

**Comment by Disasm** [comment]
Maybe this issue should be addressed to the parser: https://github.com/japaric/svd

**Comment by laanwj** [comment]
Yes, I'm not really familiar with the inner working of this tool, but that makes sense, the parser would at least need to report this to be able to report this to the user

**Comment by Disasm** [comment]
Filed a PR for this: https://github.com/japaric/svd/pull/69
However, it's just for `enumeratedValues`, maybe the same problem can happen again somewhere.
