### ISSUE TITLE
why is this "tool" not working

### ISSUE THREAD

**Issue by josephpenafiel** [rust-embedded/svd2rust#304]
I'm getting this error:

thread 'main' panicked at '/home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/svd-parser-0.6.0/src/lib.rs:361 parse::u32(t)', src/libcore/option.rs:1034:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

tried installing svd-parser, and get this error: 
error: specified package has no binaries

How is this tool supposed to be used? there's little documentation on this. I need help

**Comment by burrbull** [comment]
When does this error occur? When you install svd2rust?
```
cargo install svd2rust
```

**Comment by josephpenafiel** [comment]
when I run:
$ svd2rust -i STM32G07x.svd --target cortex-m

**Comment by burrbull** [comment]
Can you store somewhere you svd file?

And did you try [stm32g4xx-hal](https://crates.io/crates/stm32g4xx-hal) crate?

**Comment by josephpenafiel** [comment]
https://1drv.ms/u/s!AsXdvpVk4QASkI8moO6F1uGJPT0SAg

**Comment by burrbull** [comment]
You can try svd2rust from master branch:
```
cargo install svd2rust --get https://github.com/rust-embedded/svd2rust --force
```

**Comment by josephpenafiel** [comment]
Tried your suggestion but I'm still getting the error

**Comment by burrbull** [comment]
```
thread 'main' panicked at '//TODO(AJM): SVDError { inner: SVDError { inner: SVDError { inner: ParseIntError { kind: Overflow }

0x1F1F1F11F invalid }

In register `HWCFGR6` }

In peripheral `ADC` }',
```

**Comment by adamgreig** [comment]
Closing, this is a bug in the svd file rather than svd2rust. @josephpenafiel please feel free to comment again if you still can't get it working, but also consider using the stm32g0 crate.
