### ISSUE TITLE
Close issues

### ISSUE THREAD

**Issue by burrbull** [rust-embedded/svd2rust#321]
#304 - incorrect SVD (not a bug)
#247 - looks like not actual
#218, #16 - closed by #318
#250 
 
#183, #51  - c.b. #237, #317 

#190, #256  - c.b. #319
#91 - c.b. #322 
#194 - c.b. #317 

#116

**Comment by burrbull** [comment]
cc @therealprof , @Emilgardis

**Comment by burrbull** [comment]
cc @therealprof

**Comment by adamgreig** [comment]
Thanks for the triage (and all the work to resolve issues) @burrbull! I've closed most issues but leaving #16 and #116 open a little longer to ponder if they are fully resolved. But if anyone else on the team feels they can be closed please go ahead.

**Comment by adamgreig** [comment]
Oh, and I think #250 still applies - svd2rust-regress still depends on reqwest 0.8, which presumably still brings in an old ssl.
