### ISSUE TITLE
Bad news

### ISSUE THREAD

**Issue by burrbull** [rust-embedded/svd2rust#353]
cc @therealprof 

I think I made regression with `FR` field.
Now there is no access to field enums to compare they manually. It's my mistake. Big mistake.
It doesn't break most of code, but it's regression.
I think we should revert #343.

Alternative is to add `values` method to reader.

**Comment by therealprof** [comment]
Well, the release is out. But I'm not even sure that was intentional that one could do that. Do you see any usecase for that?
