### ISSUE TITLE
svd2rust-regress usability woes

### ISSUE THREAD

**Issue by therealprof** [rust-embedded/svd2rust#355]
The interface of `svd2rust-regress` is a bit iffy. On one hand internally every manufacturer and chip name is converted to a "nice" lower-case name with no special characters and this is used everywhere, also for the output of the `--list` option. On the other hand all options like `--manufacturer` and `--chip` expect to receive the unchanged original name.

Also wildcards are not supported which would be really nice to have.

Next problem is that bad tests are only listed or can be executed when the `--bad-tests` option is supplied however I'd expect to see bad tests in the listing as well (maybe with some additional marker) to know that they exists and also to execute them without having to explicitly specify that it's in the "bad tests" category when I specifically ask for a certain chip.

**Comment by burrbull** [comment]
related to #728
