### ISSUE TITLE
Enum/Reader/Writer names

### ISSUE THREAD

**Issue by burrbull** [rust-embedded/svd2rust#356]
Now we can merge `FIELDR` and `FIELDW` as they are identical.

The question is how to name it.

If name simply `FIELD` we need to rename register/field readers/writers as sometimes there are name conflicts. For example field `W`.

cc @therealprof 
cc @adamgreig

**Comment by therealprof** [comment]
`FIELD_A` with `_A` for access?

**Comment by burrbull** [comment]
And `FIELD_R`, `FIELD_W` for reader/writer?

**Comment by therealprof** [comment]
Something like that. I'm undecided about the underscore though.
