### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by burrbull** [rust-embedded/svd2rust#366]
cc @therealprof 

I think it is time for new release.

**Comment by therealprof** [comment]
I haven't checked the impact of the changes yet. Except for the unsafe fix, what do you figure is important enough to warrant a new release? And do you mean before or after #364 (which lacks the CHANGELOG entry, BTW).

**Comment by burrbull** [comment]
I think it's better to have release before 364.

That PR is serious change and we can miss a lot of bugs.

**Comment by therealprof** [comment]
Works for me. Would you mind re-checking all details (like CHANGELOG entries) and create a PR?

**Comment by burrbull** [comment]
15.3 or 16.0?

**Comment by therealprof** [comment]
The `-g` flag is a breaking change, right?

**Comment by therealprof** [comment]
Ah, I see, the default hasn't changed. But curiously the `-g` flag is not mentioned in the CHANGELOG. 😅

**Comment by therealprof** [comment]
Still the new methods in the generated code probably warrant a minor bump.

**Comment by burrbull** [comment]
> Still the new methods in the generated code probably warrant a minor bump.

Yes, `-g` is needed to simplify the change-over.

>  But curiously the `-g` flag is not mentioned in the CHANGELOG. sweat_smile

I remember.

**Comment by burrbull** [comment]
> The `-g` flag is a breaking change, right?

By itself, no. You can to not use it and you'll not see changes.
