### ISSUE TITLE
Generated code doesn't work

### ISSUE THREAD

**Issue by thejpster** [rust-embedded/svd2rust#487]
I built a PAC using svd2rust 0.17 and it didn't compile (https://github.com/rp-rs/rp2040-pac).

I had to:

* Remove a bunch of lints that rustc 1.49 didn't like
* Replace `bare_metal::Nr` with `cortex_m::interrupt::Nr`

I also really struggled with the docs, which in the SVD are full of `\n` character pairs. It would really help if svd2rust could process out these character pairs and split the docs into multiple lines.

**Comment by thejpster** [comment]
I can confirm that head works fine. See https://github.com/rp-rs/rp2040-pac/tree/use_svd_0.18alpha

**Comment by therealprof** [comment]
We were just discussing this on the `rp-rs` channel and @adamgreig mentioned that the `\n` are not really supposed to be there. We might try to filter them out in the parser if it's not too painful/expensive.

**Comment by thejpster** [comment]
I tried to do it in the generated output with sed and it was not easy at all (because you use #[doc=""] not ///). Filtering the string before it's rendered as docs would be best.

At least they didn't use Doxygen syntax in the comments 😂

**Comment by therealprof** [comment]
There's unfortunately no way to generate `///` doc strings, it's a long pet peeve of mine https://github.com/alexcrichton/proc-macro2/issues/205

**Comment by burrbull** [comment]
Is this still actual?
