### ISSUE TITLE
Allow to use only as library

### ISSUE THREAD

**Issue by Shatur** [rust-embedded/svd2rust#618]
When working with FPGA I use this crate as a build dependency library to generate code (because my FPGA configuration changes).
But this also means that I have to pull some extra deps, such as `clap`.
I would like to request to separate executable and generation library.

**Comment by Emilgardis** [comment]
This could be done by making bin deps default opt-in, and then you'll depend on svd2rust with `svd2rust = {version = "*", default-features = false}`

e.g

New feature `bin` that pulls in clap and everything else we're using in the svd2rust binary. This feature is enabled by default

this just has to be implemented, feel free to make a pr!

**Comment by Emilgardis** [comment]
I don't see the issue, binary packages can specify [`required-features`](https://doc.rust-lang.org/cargo/reference/cargo-targets.html#the-required-features-field)
