### ISSUE TITLE
if a field have doc on `read` function, then it should be put it in rust doc

### ISSUE THREAD

**Issue by eZioPan** [rust-embedded/svd2rust#733]
https://github.com/rust-embedded/svd2rust/blob/ef56dd1daeaf0048184567d306ca3d5c9d7c0208/src/generate/register.rs#LL808C89-L808C89

Currently, only doc in `write` function or the `write` side of `read-write` functions has been put into rust `#[doc = ...]`

**Comment by burrbull** [comment]
should be easy to fix.
Please, create pull request.

**Comment by eZioPan** [comment]
@burrbull would you please spare some time to check whether my modification is good?
