### ISSUE TITLE
A number of the PACs in [esp-pacs](https://github.com/esp-rs/esp-pacs/) are for RISC-V devices (everything except `esp32`, `esp32s2`, `esp32s3`, and `esp8266`).

### ISSUE THREAD

**Issue by Osvaldo23** [rust-embedded/svd2rust#787]
A number of the PACs in [esp-pacs](https://github.com/esp-rs/esp-pacs/) are for RISC-V devices (everything except `esp32`, `esp32s2`, `esp32s3`, and `esp8266`).

_Originally posted by @jessebraham in https://github.com/rust-embedded/svd2rust/issues/759#issuecomment-1827254034_

**Comment by Emilgardis** [comment]
I suspect this issue was made in error. if not, please clarify the meaning of it!
