### ISSUE TITLE
UPPER CASE, lower case and Title Case

### ISSUE THREAD

**Issue by jonathanpallant** [rust-embedded/svd2rust#803]
In Rust, we typically use `TitleCase` for types (like `struct Uart0 { .. .}`), and `lower_case` for module names (like `pac::uart0`), method/function names (like `my_uart.baudrate()`), and field names within structs (like `my_uart.baudrate`). Things that are `UPPER_CASE` are typically only static variables and constants.

The code generated by svd2rust currently uses a lot of `UPPER_CASE` names for types, and also for the field names in `struct Peripherals`. I think this can be confusing for a newcomer to Embedded Rust.

* Does anyone recall the reason for using `UPPER_CASE` here?
* Is there any appetite for changing the output to follow a more typical approach for capitalising things?

**Comment by burrbull** [comment]
You can specify it by `ident_formats.peripheral.case = pascal` in config. See https://github.com/rust-embedded/svd2rust/pull/794

**Comment by jonathanpallant** [comment]
That's cool. But why is the default the way it is?

**Comment by burrbull** [comment]
I don't have answer.
I think there is many factors you should consider: rust style, datasheet (RM) style, real names in SVD.
Any of variants like: Don't change (leave as in SVD), make constant case, make pascal case, etc. have downsides.
I think upper (constant) case was selected by @japaric just because he was working with STM32 when started the project.

**Comment by Emilgardis** [comment]
Maybe it's worth looking into changing the default to PascalCase, I can't think of any reasons to not do it except that it's a breaking change

**Comment by burrbull** [comment]
We should also split option for peripheral types and peripheral singletons. Now it is one option.

**Comment by burrbull** [comment]
:facepalm: 
There is also typos. https://github.com/rust-embedded/svd2rust/blob/869d34f935854d84fde67ef0584ee1b14e79988c/src/config.rs#L156-L159
