### ISSUE TITLE
Incorrect mapping of ZeroToSet

### ISSUE THREAD

**Issue by BigPeteB** [rust-embedded/svd2rust#826]
It looks like the fix in #673 has a bug. At https://github.com/rust-embedded/svd2rust/blame/6de189fc83268cfd5f66377c65a5aa2430de9e74/src/generate/register.rs#L858, `ZeroToSet` maps to `"BitWriter0C"`. Should this not be `"BitWriter0S"`?

**Comment by burrbull** [comment]
Yes. It's a typo.
It is strange nobody's found this yet.
Open PR, please.
